[B1,FitInfo1] = PQSQRegularRegr(Breast(:,2:end),Breast(:,1),...
    'Lambda',lambda,'Regular','lasso1');
[B2,FitInfo2] = PQSQRegularRegr(Breast(:,2:end),Breast(:,1),...
    'Lambda',lambda,'Regular',{'elasticnet3',0.5});
[B3,FitInfo3] = PQSQRegularRegr(Breast(:,2:end),Breast(:,1),...
    'Lambda',lambda,'Regular',{1,@L2,5,1});
[B4,FitInfo4] = PQSQRegularRegr(Breast(:,2:end),Breast(:,1),...
    'Lambda',lambda,'Regular',{1,@L1_5,5,1});
[B5,FitInfo5] = PQSQRegularRegr(Breast(:,2:end),Breast(:,1),...
    'Lambda',lambda,'Regular',{1,@LLog,5,1});
[B6,FitInfo6] = PQSQRegularRegr(Breast(:,2:end),Breast(:,1),...
    'Lambda',lambda,'Regular',{1,@LSqrt,5,1});
[B7,FitInfo7] = PQSQRegularRegr(Breast(:,2:end),Breast(:,1),...
    'Lambda',lambda,'Regular',{'elasticnet3',0.5},...
    'Regular',{0.5,@L1_5,5,1},'Regular',{0.5,@LLog,5,1},...
    'Regular',{0.5,@LSqrt,5,1});
sparsity = zeros(32,7);
for k=1:32 %k is number of nonzero coefficients plus 1
    sparsity(k,1) = bestError( FitInfo1, k-1 );
    sparsity(k,2) = bestError( FitInfo2, k-1 );
    sparsity(k,3) = bestError( FitInfo3, k-1 );
    sparsity(k,4) = bestError( FitInfo4, k-1 );
    sparsity(k,5) = bestError( FitInfo5, k-1 );
    sparsity(k,6) = bestError( FitInfo6, k-1 );
    sparsity(k,7) = bestError( FitInfo7, k-1 );
end